/**
 * RevenueCat scaffolding — the Convex files we drop into a project the first time
 * RevenueCat is connected, plus the env vars they read. Mirrors stripe-scaffold.ts.
 *
 *   convex/revenueCatWebhook.ts  (read-only) — verifies the platform's V2 HMAC
 *                                signature + freshness, then hands off to billing.
 *   convex/revenueCatBilling.ts  (editable)  — the app's entitlement logic.
 *
 * Env vars set on the project's Convex deployment:
 *   BOTFLOW_PROJECT_ID
 *   BOTFLOW_REVENUECAT_WEBHOOK_SECRET  (the per-project HMAC the receiver verifies)
 */
import { eq } from 'drizzle-orm';
import { getDb } from '@/db';
import { projects } from '@/db/schema';
import { sandboxWriteFile } from '@/lib/vercel-sandbox';

export const REVENUECAT_WEBHOOK_TS = `// AUTO-GENERATED by Botflow. Do not edit — the agent's write-guard will refuse changes.
//
// Convex HTTP endpoint that receives normalized RevenueCat entitlement events
// forwarded by the Botflow platform. Verifies the timestamped HMAC signature
// (so randoms can't spoof or replay events), then hands off to
// revenueCatBilling.ts (which IS editable — that's where you grant/revoke).
//
// Wire it up in convex/http.ts:
//   import { revenueCatWebhook } from "./revenueCatWebhook";
//   http.route({ path: "/revenuecat/webhook", method: "POST", handler: revenueCatWebhook });
import { httpAction } from "./_generated/server";
import { internal } from "./_generated/api";

const PROJECT_SECRET = process.env.BOTFLOW_REVENUECAT_WEBHOOK_SECRET;

async function hmacHex(secret: string, message: string): Promise<string> {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey(
    "raw",
    enc.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, enc.encode(message));
  return Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

function safeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let mismatch = 0;
  for (let i = 0; i < a.length; i++) mismatch |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return mismatch === 0;
}

export const revenueCatWebhook = httpAction(async (ctx, req) => {
  if (!PROJECT_SECRET) {
    return new Response("RevenueCat integration not configured", { status: 500 });
  }
  const raw = await req.text();

  // Require the timestamped V2 signature: HMAC("<timestamp>.<body>") within 5
  // minutes. Binding a fresh timestamp blocks replay of a captured request.
  const tsHeader = req.headers.get("X-Botflow-Timestamp");
  const sigV2 = req.headers.get("X-Botflow-Signature-V2");
  if (!tsHeader || !sigV2) {
    return new Response("missing signature", { status: 401 });
  }
  const ts = Number(tsHeader);
  const nowSec = Math.floor(Date.now() / 1000);
  if (!Number.isFinite(ts) || Math.abs(nowSec - ts) > 300) {
    return new Response("stale or invalid timestamp", { status: 401 });
  }
  const expected = await hmacHex(PROJECT_SECRET, ts + "." + raw);
  if (!safeEqual(sigV2, expected)) {
    return new Response("bad signature", { status: 401 });
  }

  let event: { type: string; id: string; data?: unknown };
  try {
    event = JSON.parse(raw);
  } catch {
    return new Response("invalid json", { status: 400 });
  }

  await ctx.runMutation(internal.revenueCatBilling.applyRevenueCatEvent, { event });
  return new Response("ok", { status: 200 });
});
`;

export const REVENUECAT_BILLING_TS = `// EDITABLE — implement how RevenueCat entitlement events change your app here.
//
// The payload is a NORMALIZED Botflow event — NOT a raw RevenueCat event.
// event.type is one of:
//   entitlement.granted       — purchase / renewal / uncancellation / trial
//   entitlement.revoked       — expired (access ended)
//   entitlement.cancellation  — auto-renew turned off (access usually continues
//                               until expiration — do NOT revoke here)
//   billing.issue             — a renewal payment failed
//
// event.data fields: { appUserId, productId, entitlementIds, expirationAtMs,
//   store, environment, price, currency, rcEventType, rawAppUserId }
//
// ⚠️ appUserId is your app's OWN user id (the platform strips its bfp_<projectId>__
//    routing prefix before delivery). Match your users on event.data.appUserId.
// ⚠️ environment is "SANDBOX" or "PRODUCTION" — gate so sandbox test purchases
//    don't change production entitlement state.
// ⚠️ IDEMPOTENCY: delivery is at-least-once — guard additive actions with event.id.

import { internalMutation } from "./_generated/server";
import { v } from "convex/values";

export const applyRevenueCatEvent = internalMutation({
  args: { event: v.any() },
  handler: async (ctx, { event }) => {
    const type = event.type as string;
    const data = (event.data ?? {}) as Record<string, any>;
    const appUserId = data.appUserId as string | undefined;
    const environment = data.environment as string | undefined;
    console.log("[revenueCatWebhook]", type, event.id, "appUserId:", appUserId, "env:", environment);
    if (!appUserId) return;

    // ── Adapt to YOUR schema. Example: a "userProfiles" table indexed by
    // ── appUserId with an "entitled" boolean.
    if (type === "entitlement.granted") {
      // const profile = await ctx.db.query("userProfiles")
      //   .withIndex("by_appUserId", (q) => q.eq("appUserId", appUserId)).unique();
      // if (profile) await ctx.db.patch(profile._id, { entitled: true });
      console.log("[revenueCatWebhook] would grant entitlement", appUserId);
    } else if (type === "entitlement.revoked") {
      // if (profile) await ctx.db.patch(profile._id, { entitled: false });
      console.log("[revenueCatWebhook] would revoke entitlement", appUserId);
    }
    // entitlement.cancellation / billing.issue: usually keep access; surface a
    // "renew" or "fix payment" prompt instead of revoking.
  },
});
`;

/** Set the Convex env vars the scaffolded RevenueCat receiver reads. Idempotent. */
export async function setRevenueCatConvexEnv(
  projectId: string,
): Promise<{ ok: true } | { ok: false; error: string }> {
  const db = getDb();
  const [project] = await db.select().from(projects).where(eq(projects.id, projectId));
  if (!project) return { ok: false, error: 'Project not found' };
  if (!project.revenuecatWebhookSecret) {
    return { ok: false, error: 'Project has no RevenueCat webhook secret' };
  }

  const deployUrl = project.backendType === 'user' ? project.userConvexUrl : project.convexDeployUrl;
  const deployKey = project.backendType === 'user' ? project.userConvexDeployKey : project.convexDeployKey;
  if (!deployUrl || !deployKey) {
    return { ok: false, error: 'Convex deployment is not configured for this project' };
  }

  const vars = {
    BOTFLOW_PROJECT_ID: projectId,
    BOTFLOW_REVENUECAT_WEBHOOK_SECRET: project.revenuecatWebhookSecret,
  };
  const changes = Object.entries(vars).map(([name, value]) => ({ name, value }));
  const res = await fetch(`${deployUrl}/api/update_environment_variables`, {
    method: 'POST',
    headers: { Authorization: `Convex ${deployKey}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ changes }),
  });
  if (!res.ok) {
    // Don't echo the upstream body — the payload carries the secret.
    await res.text().catch(() => '');
    return { ok: false, error: `Failed to set Convex env (status ${res.status})` };
  }
  return { ok: true };
}

/**
 * Inject the /revenuecat/webhook route into an existing convex/http.ts so the
 * platform's signed deliveries actually reach the receiver (otherwise they 404
 * before verification). Returns the updated source, or null if already wired /
 * shape unrecognized (the agent guidance covers that fallback).
 */
export function wireRevenueCatRoute(httpSrc: string): string | null {
  if (httpSrc.includes('/revenuecat/webhook')) return null; // already wired
  // Only touch a genuine Convex http router file.
  if (!/httpRouter\s*\(/.test(httpSrc)) return null;
  const exportMatch = httpSrc.match(/export\s+default\s+(\w+)\s*;?/);
  if (!exportMatch) return null;
  const routerVar = exportMatch[1];
  // The exported identifier must actually be the httpRouter() instance, or we'd
  // inject `<word>.route(...)` against something that isn't a router.
  const routerDecl = new RegExp(`(?:const|let|var)\\s+${routerVar}\\s*=\\s*httpRouter\\s*\\(`);
  if (!routerDecl.test(httpSrc)) return null;

  let src = httpSrc;
  // Detect an existing import regardless of quote style before adding one.
  if (!/from\s+["']\.\/revenueCatWebhook["']/.test(src)) {
    const importLine = 'import { revenueCatWebhook } from "./revenueCatWebhook";';
    const lastImport = src.lastIndexOf('\nimport ');
    if (lastImport >= 0) {
      const eol = src.indexOf('\n', lastImport + 1);
      src = src.slice(0, eol + 1) + importLine + '\n' + src.slice(eol + 1);
    } else {
      src = importLine + '\n' + src;
    }
  }
  const routeLine = `${routerVar}.route({ path: "/revenuecat/webhook", method: "POST", handler: revenueCatWebhook });`;
  src = src.replace(exportMatch[0], `${routeLine}\n\n${exportMatch[0]}`);
  return src;
}

/** Drop the receiver/billing files into the project's /convex and set env vars. */
export async function scaffoldRevenueCatIntoProject(projectId: string): Promise<{
  filesWritten: string[];
  envSet: boolean;
  routeWired: boolean;
  envError?: string;
  filesError?: string;
}> {
  const { sandboxReadFile } = await import('@/lib/vercel-sandbox');
  const written: string[] = [];
  let filesError: string | undefined;
  let routeWired = false;
  try {
    // Always re-write the read-only receiver.
    await sandboxWriteFile(projectId, '/convex/revenueCatWebhook.ts', REVENUECAT_WEBHOOK_TS);
    written.push('/convex/revenueCatWebhook.ts');
    // Only seed billing if missing — the agent owns it.
    const existing = await sandboxReadFile(projectId, '/convex/revenueCatBilling.ts').catch(() => null);
    if (!existing || !existing.content) {
      await sandboxWriteFile(projectId, '/convex/revenueCatBilling.ts', REVENUECAT_BILLING_TS);
      written.push('/convex/revenueCatBilling.ts');
    }
    // Mount the route in convex/http.ts so deliveries don't 404. If http.ts
    // doesn't exist yet (no auth set up), the agent wires it per guidance.
    const http = await sandboxReadFile(projectId, '/convex/http.ts').catch(() => null);
    if (http && http.content) {
      const updated = wireRevenueCatRoute(http.content);
      if (updated) {
        await sandboxWriteFile(projectId, '/convex/http.ts', updated);
        written.push('/convex/http.ts');
        routeWired = true;
      } else if (http.content.includes('/revenuecat/webhook')) {
        routeWired = true; // already mounted
      }
    }
  } catch (err) {
    filesError = err instanceof Error ? err.message : String(err);
    console.error('[revenuecat-scaffold] file drop failed:', err);
  }

  const envResult = await setRevenueCatConvexEnv(projectId).catch((err) => ({
    ok: false as const,
    error: err instanceof Error ? err.message : String(err),
  }));

  return {
    filesWritten: written,
    envSet: envResult.ok === true,
    routeWired,
    ...(envResult.ok === true ? {} : { envError: envResult.error }),
    ...(filesError ? { filesError } : {}),
  };
}
