/**
 * RevenueCat scaffolding — the Convex files we drop into a Swift+Convex project's
 * sandbox once RevenueCat is connected (or already-connected).
 *
 * Mirrors stripe-scaffold.ts, but for the iOS in-app-purchase flow:
 *   /convex/revenueCatWebhook.ts  — read-only httpAction; verifies the platform
 *       HMAC and hands off to billing.ts. (Receives entitlement events forwarded
 *       by /api/webhooks/revenuecat.)
 *   /convex/billing.ts            — EDITABLE; where the agent reacts to events
 *       (e.g. mirror subscription state into a Convex table for server logic).
 *   /convex/http.ts               — ensured to route POST /revenuecat/webhook.
 *
 * Plus Convex env vars the webhook file reads:
 *   BOTFLOW_PROJECT_ID
 *   BOTFLOW_REVENUECAT_PROXY_BASE
 *   BOTFLOW_REVENUECAT_WEBHOOK_SECRET
 *   REVENUECAT_ENVIRONMENT
 *
 * Unlike Stripe, entitlement checks happen on-device via the RevenueCat SDK, so
 * there's no outbound platform proxy file to scaffold — Convex only RECEIVES.
 */
import { eq } from 'drizzle-orm';
import { getDb } from '@/db';
import { projects } from '@/db/schema';
import { sandboxWriteFile, sandboxReadFile } from '@/lib/vercel-sandbox';

// ───────────────────────── templates ──────────────────────────

export const REVENUECAT_WEBHOOK_TS = `// AUTO-GENERATED by Botflow. Do not edit — the agent's write-guard will refuse changes.
//
// Convex HTTP endpoint that receives normalized RevenueCat entitlement events
// forwarded by the Botflow platform. Verifies the HMAC signature (so randoms
// can't spoof events), then hands off to billing.ts (which IS editable — that's
// where the agent mirrors entitlement state into your tables).
//
// Wired up via convex/http.ts:
//   http.route({ path: "/revenuecat/webhook", method: "POST", handler: revenueCatWebhook });
import { httpAction } from "./_generated/server";
import { internal } from "./_generated/api";

const PROJECT_SECRET = process.env.BOTFLOW_REVENUECAT_WEBHOOK_SECRET;

async function hmacHex(secret: string, message: string): Promise<string> {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey(
    "raw",
    enc.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, enc.encode(message));
  return Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

function safeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let mismatch = 0;
  for (let i = 0; i < a.length; i++) mismatch |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return mismatch === 0;
}

export const revenueCatWebhook = httpAction(async (ctx, req) => {
  if (!PROJECT_SECRET) {
    return new Response("RevenueCat integration not configured", { status: 500 });
  }
  const signatureHeader = req.headers.get("X-Botflow-Signature");
  if (!signatureHeader) return new Response("missing signature", { status: 401 });

  const raw = await req.text();
  const expected = await hmacHex(PROJECT_SECRET, raw);
  if (!safeEqual(signatureHeader, expected)) {
    return new Response("bad signature", { status: 401 });
  }

  let event: { type: string; id: string; data?: unknown };
  try {
    event = JSON.parse(raw);
  } catch {
    return new Response("invalid json", { status: 400 });
  }

  await ctx.runMutation(internal.billing.applyRevenueCatEvent, { event });
  return new Response("ok", { status: 200 });
});
`;

export const BILLING_TS = `// EDITABLE — implement how RevenueCat entitlement events change your app's
// database here. revenueCatWebhook.ts calls applyRevenueCatEvent below, so this
// is the single place your server-side subscription/entitlement logic lives.
//
// NOTE: on iOS the RevenueCat SDK is the source of truth for what the user can
// access RIGHT NOW (check Purchases.shared.customerInfo().entitlements on-device).
// This webhook is for SERVER-SIDE state — e.g. mirroring "is this user pro" into
// a Convex table so your backend functions can gate features too.
//
// The payload is a NORMALIZED Botflow event — NOT a raw RevenueCat event. Handle
// these event.type values, with these event.data fields:
//
//   entitlement.granted      — purchase / renewal / uncancellation / product change
//       data: { appUserId, productId, entitlementIds, periodType, expirationAtMs, store, environment, price, currency, rcEventType }
//   entitlement.revoked      — access ended (subscription expired)
//       data: { appUserId, productId, entitlementIds, expirationAtMs, environment, expirationReason, rcEventType }
//   entitlement.cancellation — auto-renew turned off (access usually continues until expiration)
//       data: { appUserId, productId, entitlementIds, expirationAtMs, cancelReason, rcEventType }
//   billing.issue            — a renewal payment failed
//       data: { appUserId, productId, entitlementIds, environment, rcEventType }
//
// ── LINKING AN EVENT TO ONE OF YOUR USERS ──────────────────────────────────
// The app sets the RevenueCat App User ID at launch:
//   Purchases.configure(withAPIKey: <key>, appUserID: <your user's id>)
// That id comes back here as event.data.appUserId. Make sure the app configures
// RevenueCat with your real user id (not an anonymous id) so this mapping works.

import { internalMutation } from "./_generated/server";
import { v } from "convex/values";

export const applyRevenueCatEvent = internalMutation({
  args: { event: v.any() },
  handler: async (ctx, { event }) => {
    const type = event.type as string;
    const data = (event.data ?? {}) as Record<string, any>;

    const appUserId = data?.appUserId as string | undefined;
    console.log("[revenueCatWebhook]", type, event.id, "appUserId:", appUserId);
    if (!appUserId) return; // can't map the event to a user without it

    // ── Adapt the lines below to YOUR schema. This example assumes a
    // ── "userProfiles" table indexed by userId ("by_userId") with a "tier".
    if (type === "entitlement.granted") {
      // const profile = await ctx.db.query("userProfiles")
      //   .withIndex("by_userId", (q) => q.eq("userId", appUserId as any))
      //   .unique();
      // if (profile) {
      //   await ctx.db.patch(profile._id, {
      //     tier: "pro",
      //     entitlementExpiresAtMs: data.expirationAtMs ?? null,
      //     lastProductId: data.productId,
      //   });
      // }
      console.log("[revenueCatWebhook] would grant access", appUserId, data.entitlementIds);
    } else if (type === "entitlement.revoked") {
      // const profile = await ctx.db.query("userProfiles")
      //   .withIndex("by_userId", (q) => q.eq("userId", appUserId as any))
      //   .unique();
      // if (profile) await ctx.db.patch(profile._id, { tier: "free" });
      console.log("[revenueCatWebhook] would revoke access", appUserId);
    } else if (type === "entitlement.cancellation") {
      // Auto-renew off but access likely continues until expirationAtMs.
      console.log("[revenueCatWebhook] auto-renew off (access until expiry)", appUserId);
    } else if (type === "billing.issue") {
      console.log("[revenueCatWebhook] billing issue — may enter grace period", appUserId);
    }
  },
});
`;

// ───────────────────────── http.ts wiring ──────────────────────────

const HTTP_TS_FRESH = `// AUTO-GENERATED by Botflow.
import { httpRouter } from "convex/server";
import { revenueCatWebhook } from "./revenueCatWebhook";

const http = httpRouter();

http.route({ path: "/revenuecat/webhook", method: "POST", handler: revenueCatWebhook });

export default http;
`;

const ROUTE_IMPORT = `import { revenueCatWebhook } from "./revenueCatWebhook";`;
const ROUTE_LINE = `http.route({ path: "/revenuecat/webhook", method: "POST", handler: revenueCatWebhook });`;

/**
 * Ensure /convex/http.ts routes POST /revenuecat/webhook → revenueCatWebhook.
 * - Missing file → write a complete one.
 * - Present, already wired → leave it.
 * - Present, not wired → inject the import + route line (best-effort). If the
 *   expected `export default http` anchor isn't found, leave the file untouched
 *   and rely on the agent (the prompt instructs it) rather than risk corruption.
 *
 * Returns a short status for logging. Never throws.
 */
export async function ensureRevenueCatHttpRoute(
  projectId: string,
): Promise<'created' | 'already' | 'injected' | 'manual'> {
  const existing = await sandboxReadFile(projectId, '/convex/http.ts').catch(() => null);
  if (!existing || !existing.content) {
    await sandboxWriteFile(projectId, '/convex/http.ts', HTTP_TS_FRESH);
    return 'created';
  }
  const src = existing.content;
  if (src.includes('revenueCatWebhook')) return 'already';

  // Inject the route before `export default http`.
  const anchorMatch = src.match(/export\s+default\s+http\s*;?/);
  if (!anchorMatch) return 'manual'; // unfamiliar shape — don't risk it

  const importBlock = src.includes(ROUTE_IMPORT) ? '' : `${ROUTE_IMPORT}\n`;
  const withImport = importBlock
    // Put the import after the last existing import line for tidiness; fall back
    // to prepending if no import lines exist.
    ? (() => {
        const importLines = [...src.matchAll(/^import .*$/gm)];
        if (importLines.length === 0) return importBlock + src;
        const last = importLines[importLines.length - 1];
        const idx = (last.index ?? 0) + last[0].length;
        return src.slice(0, idx) + `\n${ROUTE_IMPORT}` + src.slice(idx);
      })()
    : src;

  const injected = withImport.replace(
    anchorMatch[0],
    `${ROUTE_LINE}\n\n${anchorMatch[0]}`,
  );
  await sandboxWriteFile(projectId, '/convex/http.ts', injected);
  return 'injected';
}

// ───────────────────────── apply to sandbox ──────────────────────────

/**
 * Drop the RevenueCat Convex files into the project's sandbox. Idempotent —
 * revenueCatWebhook.ts is always overwritten (read-only by intent); billing.ts
 * is only created if missing (the agent edits it); http.ts is ensured.
 *
 * Returns the list of paths written + the http.ts wiring status.
 */
export async function dropRevenueCatFilesIntoSandbox(
  projectId: string,
): Promise<{ written: string[]; httpStatus: string }> {
  const written: string[] = [];

  await sandboxWriteFile(projectId, '/convex/revenueCatWebhook.ts', REVENUECAT_WEBHOOK_TS);
  written.push('/convex/revenueCatWebhook.ts');

  // Only seed billing.ts if missing — the agent owns this file.
  const existing = await sandboxReadFile(projectId, '/convex/billing.ts').catch(() => null);
  if (!existing || !existing.content) {
    await sandboxWriteFile(projectId, '/convex/billing.ts', BILLING_TS);
    written.push('/convex/billing.ts');
  }

  const httpStatus = await ensureRevenueCatHttpRoute(projectId);
  if (httpStatus === 'created' || httpStatus === 'injected') {
    written.push('/convex/http.ts');
  }

  return { written, httpStatus };
}

/** Promise.race-with-timeout, never throws. */
function withTimeout<T>(p: Promise<T>, ms: number, label: string): Promise<T> {
  return Promise.race([
    p,
    new Promise<T>((_, rej) => setTimeout(() => rej(new Error(`${label} timed out after ${ms}ms`)), ms)),
  ]);
}

/**
 * Set the Convex env vars the scaffolded files read. Mirrors setStripeConvexEnv.
 */
export async function setRevenueCatConvexEnv(
  projectId: string,
  opts: { webhookSecret: string; proxyBase?: string; environment?: string },
): Promise<{ ok: true } | { ok: false; error: string }> {
  const db = getDb();
  const [project] = await db.select().from(projects).where(eq(projects.id, projectId));
  if (!project) return { ok: false, error: 'Project not found' };

  const deployUrl = project.backendType === 'user' ? project.userConvexUrl : project.convexDeployUrl;
  const deployKey = project.backendType === 'user' ? project.userConvexDeployKey : project.convexDeployKey;
  if (!deployUrl || !deployKey) {
    return { ok: false, error: 'Convex deployment is not configured for this project' };
  }

  const vars = {
    BOTFLOW_PROJECT_ID: projectId,
    BOTFLOW_REVENUECAT_PROXY_BASE: opts.proxyBase ?? 'https://botflow.io',
    BOTFLOW_REVENUECAT_WEBHOOK_SECRET: opts.webhookSecret,
    REVENUECAT_ENVIRONMENT: opts.environment ?? 'sandbox',
  };
  const changes = Object.entries(vars).map(([name, value]) => ({ name, value }));
  const res = await fetch(`${deployUrl}/api/update_environment_variables`, {
    method: 'POST',
    headers: { Authorization: `Convex ${deployKey}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ changes }),
  });
  if (!res.ok) {
    const text = await res.text();
    return { ok: false, error: `Failed to set Convex env (${res.status}): ${text.slice(0, 300)}` };
  }
  return { ok: true };
}

/**
 * One-call helper: drop the files AND set the env vars. The connect / initialize
 * endpoints call this after RevenueCat becomes connected. Failures are logged
 * but non-fatal.
 */
export async function scaffoldRevenueCatIntoProject(
  projectId: string,
  opts: { webhookSecret: string; proxyBase?: string; environment?: string },
): Promise<{
  filesWritten: string[];
  httpStatus?: string;
  envSet: boolean;
  envError?: string;
  filesError?: string;
}> {
  let filesWritten: string[] = [];
  let httpStatus: string | undefined;
  let filesError: string | undefined;
  try {
    const result = await withTimeout(
      dropRevenueCatFilesIntoSandbox(projectId),
      15_000,
      'dropRevenueCatFilesIntoSandbox',
    );
    filesWritten = result.written;
    httpStatus = result.httpStatus;
  } catch (err) {
    filesError = err instanceof Error ? err.message : String(err);
    console.error('[revenuecat-scaffold] file drop failed:', err);
  }

  const envResult = await withTimeout(
    setRevenueCatConvexEnv(projectId, opts),
    10_000,
    'setRevenueCatConvexEnv',
  ).catch((err) => ({
    ok: false as const,
    error: err instanceof Error ? err.message : String(err),
  }));

  return {
    filesWritten,
    ...(httpStatus ? { httpStatus } : {}),
    envSet: envResult.ok === true,
    ...(envResult.ok === true ? {} : { envError: envResult.error }),
    ...(filesError ? { filesError } : {}),
  };
}
