/**
 * Frontend env-var materialization for sandboxed-web projects.
 *
 * Source of truth: the `project_env_vars` table (frontend/Vite vars only).
 * The sandbox `/vercel/sandbox/.env` file is a *derived artifact* — we
 * regenerate it wholesale from the DB at three moments:
 *   1. every save in the workspace Env panel,
 *   2. dev-server start (`startSandboxDevServer`),
 *   3. production build (`publish` route).
 *
 * "DB wins": this overwrites `.env` entirely. The one var we always inject is
 * the platform-enforced Convex URL (`VITE_CONVEX_URL`, or `EXPO_PUBLIC_CONVEX_URL`
 * on mobile/multiplatform), so the frontend can always reach its backend even
 * if the user never typed it.
 *
 * Backend (Convex) env vars are NOT handled here — the Convex deployment is
 * their source of truth (see `convex-env.ts`).
 */
import { eq } from "drizzle-orm";
import { getDb } from "@/db";
import { projects, projectEnvVars } from "@/db/schema";
import { writeSandboxEnvFile, sandboxWriteFile } from "@/lib/vercel-sandbox";

/**
 * The platform-managed frontend var that wires the Vite app to its Convex
 * backend. Mobile/Expo uses a different prefix. Returns null when the project
 * has no backend (nothing to inject).
 */
export function platformConvexEnvVar(
  project: typeof projects.$inferSelect,
): { key: string; value: string } | null {
  if (project.backendType === "none") return null;
  const effectiveConvexUrl = project.userConvexUrl || project.convexDeployUrl;
  if (!effectiveConvexUrl) return null;
  const key =
    project.platform === "mobile" || project.platform === "multiplatform"
      ? "EXPO_PUBLIC_CONVEX_URL"
      : "VITE_CONVEX_URL";
  return { key, value: effectiveConvexUrl };
}

/**
 * Build the full frontend env map (DB rows + the injected platform var).
 * The platform var always wins over any user row with the same key.
 */
export async function buildFrontendEnvMap(
  projectId: string,
): Promise<Record<string, string>> {
  const db = getDb();
  const [project] = await db.select().from(projects).where(eq(projects.id, projectId));
  if (!project) return {};

  const env: Record<string, string> = {};

  const userVars = await db
    .select()
    .from(projectEnvVars)
    .where(eq(projectEnvVars.projectId, projectId));
  for (const row of userVars) {
    if (row.key) env[row.key] = row.value ?? "";
  }

  const platformVar = platformConvexEnvVar(project);
  if (platformVar) env[platformVar.key] = platformVar.value;

  return env;
}

/**
 * Regenerate `/vercel/sandbox/.env` from the DB. Safe to call repeatedly.
 * Throws if the sandbox write fails so callers can decide whether it's fatal
 * (dev-server start) or best-effort (panel save).
 */
export async function materializeFrontendEnv(projectId: string): Promise<void> {
  const env = await buildFrontendEnvMap(projectId);
  await writeSandboxEnvFile(projectId, env);
}

// ────────────────────────────────────────────────────────────────────────────
// Swift Convex config injection
// ────────────────────────────────────────────────────────────────────────────

/** Project-relative path of the platform-managed Swift Convex config file. */
const SWIFT_CONVEX_CONFIG_PATH = "/Sources/Core/ConvexConfig.swift";

/**
 * Render the generated `ConvexConfig.swift`. This is the Swift analog of
 * `VITE_CONVEX_URL` — instead of a `.env` value the frontend reads at runtime,
 * Swift gets a compile-time constant baked into the app. Must match the shape
 * of the committed placeholder in the swift-convex-template.
 */
export function swiftConvexConfigContent(convexUrl: string): string {
  // JSON.stringify gives us a safely-quoted Swift string literal too.
  const literal = JSON.stringify(convexUrl);
  return [
    "// ─────────────────────────────────────────────────────────────────",
    "// ConvexConfig.swift — Convex deployment URL (PLATFORM-MANAGED)",
    "//",
    "// ⚠️  GENERATED BY BOTFLOW — DO NOT EDIT BY HAND.",
    "// Regenerated from the project's Convex deployment before each build.",
    "// ─────────────────────────────────────────────────────────────────",
    "",
    "import Foundation",
    "",
    "enum ConvexConfig {",
    `    static let url = ${literal}`,
    "    static var isPlaceholder: Bool { url.contains(\"placeholder\") }",
    "}",
    "",
  ].join("\n");
}

/**
 * Write `Sources/Core/ConvexConfig.swift` into a Swift project's sandbox with
 * the project's effective Convex URL (BYOC `userConvexUrl` wins over the
 * platform `convexDeployUrl`, mirroring `platformConvexEnvVar`).
 *
 * No-op when the project has no backend, isn't provisioned yet, or isn't Swift —
 * in those cases the committed template placeholder stays in place so the app
 * still compiles. Call this just before tarring for the simulator
 * (swift-preview start/rebuild).
 */
export async function materializeSwiftConvexConfig(projectId: string): Promise<void> {
  const db = getDb();
  const [project] = await db.select().from(projects).where(eq(projects.id, projectId));
  if (!project || project.platform !== "swift") return;
  if (project.backendType === "none") return;

  const convexUrl = project.userConvexUrl || project.convexDeployUrl;
  if (!convexUrl) return; // not provisioned yet — leave the placeholder

  await sandboxWriteFile(
    projectId,
    SWIFT_CONVEX_CONFIG_PATH,
    swiftConvexConfigContent(convexUrl),
  );
}
