/**
 * Frontend env-var materialization for sandboxed-web projects.
 *
 * Source of truth: the `project_env_vars` table (frontend/Vite vars only).
 * The sandbox `/vercel/sandbox/.env` file is a *derived artifact* — we
 * regenerate it wholesale from the DB at three moments:
 *   1. every save in the workspace Env panel,
 *   2. dev-server start (`startSandboxDevServer`),
 *   3. production build (`publish` route).
 *
 * "DB wins": this overwrites `.env` entirely. The one var we always inject is
 * the platform-enforced Convex URL (`VITE_CONVEX_URL`, or `EXPO_PUBLIC_CONVEX_URL`
 * on mobile/multiplatform), so the frontend can always reach its backend even
 * if the user never typed it.
 *
 * Backend (Convex) env vars are NOT handled here — the Convex deployment is
 * their source of truth (see `convex-env.ts`).
 */
import { eq } from "drizzle-orm";
import { getDb } from "@/db";
import { projects, projectEnvVars, userRevenueCatIdentity } from "@/db/schema";
import { writeSandboxEnvFile, sandboxWriteFile } from "@/lib/vercel-sandbox";
import { namespacedAppUserIdPrefix } from "@/lib/revenuecat-app-user-id";
import { REVENUECAT_ENABLED } from "@/lib/feature-flags";

/**
 * The platform-managed frontend var that wires the Vite app to its Convex
 * backend. Mobile/Expo uses a different prefix. Returns null when the project
 * has no backend (nothing to inject).
 */
export function platformConvexEnvVar(
  project: typeof projects.$inferSelect,
): { key: string; value: string } | null {
  if (project.backendType === "none") return null;
  const effectiveConvexUrl = project.userConvexUrl || project.convexDeployUrl;
  if (!effectiveConvexUrl) return null;
  const key =
    project.platform === "mobile" || project.platform === "multiplatform"
      ? "EXPO_PUBLIC_CONVEX_URL"
      : "VITE_CONVEX_URL";
  return { key, value: effectiveConvexUrl };
}

/**
 * Build the full frontend env map (DB rows + the injected platform var).
 * The platform var always wins over any user row with the same key.
 */
export async function buildFrontendEnvMap(
  projectId: string,
): Promise<Record<string, string>> {
  const db = getDb();
  const [project] = await db.select().from(projects).where(eq(projects.id, projectId));
  if (!project) return {};

  const env: Record<string, string> = {};

  const userVars = await db
    .select()
    .from(projectEnvVars)
    .where(eq(projectEnvVars.projectId, projectId));
  for (const row of userVars) {
    if (row.key) env[row.key] = row.value ?? "";
  }

  const platformVar = platformConvexEnvVar(project);
  if (platformVar) env[platformVar.key] = platformVar.value;

  return env;
}

/**
 * Regenerate `/vercel/sandbox/.env` from the DB. Safe to call repeatedly.
 * Throws if the sandbox write fails so callers can decide whether it's fatal
 * (dev-server start) or best-effort (panel save).
 */
export async function materializeFrontendEnv(projectId: string): Promise<void> {
  const env = await buildFrontendEnvMap(projectId);
  await writeSandboxEnvFile(projectId, env);
}

// ────────────────────────────────────────────────────────────────────────────
// Swift Convex config injection
// ────────────────────────────────────────────────────────────────────────────

/** Project-relative path of the platform-managed Swift Convex config file. */
const SWIFT_CONVEX_CONFIG_PATH = "/Sources/Core/ConvexConfig.swift";

/**
 * Render the generated `ConvexConfig.swift`. This is the Swift analog of
 * `VITE_CONVEX_URL` — instead of a `.env` value the frontend reads at runtime,
 * Swift gets a compile-time constant baked into the app. Must match the shape
 * of the committed placeholder in the swift-convex-template.
 */
export function swiftConvexConfigContent(convexUrl: string, authEnabled = false): string {
  // JSON.stringify gives us a safely-quoted Swift string literal too.
  const literal = JSON.stringify(convexUrl);
  // NOTE: this shape must stay in sync with the template's committed
  // Sources/Core/ConvexConfig.swift — the Swift client (ConvexClient+Shared,
  // BotflowAuthProvider) references `authEnabled` and `siteURL`.
  return [
    "// ─────────────────────────────────────────────────────────────────",
    "// ConvexConfig.swift — Convex deployment URL (PLATFORM-MANAGED)",
    "//",
    "// ⚠️  GENERATED BY BOTFLOW — DO NOT EDIT BY HAND.",
    "// Regenerated from the project's Convex deployment before each build.",
    "// ─────────────────────────────────────────────────────────────────",
    "",
    "import Foundation",
    "",
    "enum ConvexConfig {",
    `    static let url = ${literal}`,
    `    static let authEnabled = ${authEnabled ? "true" : "false"}`,
    "    static var isPlaceholder: Bool { url.contains(\"placeholder\") }",
    "    static var siteURL: String {",
    "        url.replacingOccurrences(of: \".convex.cloud\", with: \".convex.site\")",
    "    }",
    "}",
    "",
  ].join("\n");
}

/**
 * Write `Sources/Core/ConvexConfig.swift` into a Swift project's sandbox with
 * the project's effective Convex URL (BYOC `userConvexUrl` wins over the
 * platform `convexDeployUrl`, mirroring `platformConvexEnvVar`).
 *
 * No-op when the project has no backend, isn't provisioned yet, or isn't Swift —
 * in those cases the committed template placeholder stays in place so the app
 * still compiles. Call this just before tarring for the simulator
 * (swift-preview start/rebuild).
 */
export async function materializeSwiftConvexConfig(projectId: string): Promise<void> {
  const db = getDb();
  const [project] = await db.select().from(projects).where(eq(projects.id, projectId));
  if (!project || project.platform !== "swift") return;
  if (project.backendType === "none") return;

  const convexUrl = project.userConvexUrl || project.convexDeployUrl;
  if (!convexUrl) return; // not provisioned yet — leave the placeholder

  await sandboxWriteFile(
    projectId,
    SWIFT_CONVEX_CONFIG_PATH,
    swiftConvexConfigContent(convexUrl, project.authConfigured === true),
  );
}

// ────────────────────────────────────────────────────────────────────────────
// Swift RevenueCat config injection
// ────────────────────────────────────────────────────────────────────────────

/** Project-relative path of the platform-managed Swift RevenueCat config file. */
const SWIFT_REVENUECAT_CONFIG_PATH = "/Sources/Core/RevenueCatConfig.swift";

/**
 * Which key gets baked. Botflow's payments model for Swift is FIXED (unlike
 * web/Stripe's test-mode toggle): development builds are ALWAYS test mode
 * (RevenueCat Test Store — simulated purchases, no real money), and App Store
 * builds are ALWAYS production (the user's appl_ key + live products).
 *   'dev'     — simulator preview + dev device installs + sandbox reseeds
 *   'release' — App Store submit (swift-publish)
 */
export type SwiftBuildKind = "dev" | "release";

/**
 * Pick the only SDK key a given Swift build is allowed to receive.
 *
 * A development build must never fall back to the live App Store key. If the
 * RevenueCat Test Store has not been configured yet, we deliberately emit an
 * empty key; `RevenueCatConfig.isConfigured` then keeps Purchases unconfigured
 * instead of creating an ambiguous or potentially live payment path.
 */
export function selectSwiftRevenueCatConfig(
  keys: { productionSdkKey: string | null; testStoreSdkKey: string | null },
  buildKind: SwiftBuildKind,
): { sdkKey: string | null; isTestStore: boolean } {
  if (buildKind === "dev") {
    return keys.testStoreSdkKey
      ? { sdkKey: keys.testStoreSdkKey, isTestStore: true }
      : { sdkKey: null, isTestStore: false };
  }

  return { sdkKey: keys.productionSdkKey, isTestStore: false };
}

/**
 * Render the generated `RevenueCatConfig.swift` — how the SDK key and the
 * project-namespaced App User ID prefix reach the app. The agent prompt tells
 * the agent to call `Purchases.configure(withAPIKey: RevenueCatConfig.apiKey,
 * appUserID: RevenueCatConfig.namespacedAppUserId(<its user id>))` and never
 * hardcode a key, so this file MUST exist in every Swift project (empty key
 * until the user connects — `isConfigured` lets the app guard).
 */
export function swiftRevenueCatConfigContent(
  publicSdkKey: string | null,
  appUserIdPrefix: string,
  isTestStore: boolean,
): string {
  const keyLiteral = JSON.stringify(publicSdkKey ?? "");
  const prefixLiteral = JSON.stringify(appUserIdPrefix);
  return [
    "// ─────────────────────────────────────────────────────────────────",
    "// RevenueCatConfig.swift — RevenueCat SDK key (PLATFORM-MANAGED)",
    "//",
    "// ⚠️  GENERATED BY BOTFLOW — DO NOT EDIT BY HAND.",
    "// Regenerated from the user's RevenueCat connection before each build.",
    "// Dev builds carry the TEST STORE key (simulated purchases, no real",
    "// money); App Store builds carry the production appl_ key.",
    "// ─────────────────────────────────────────────────────────────────",
    "",
    "import Foundation",
    "",
    "enum RevenueCatConfig {",
    `    /// SDK key. Empty until RevenueCat is connected in the Payments tab —`,
    `    /// gate Purchases.configure on isConfigured.`,
    `    static let apiKey = ${keyLiteral}`,
    `    /// True when this build uses RevenueCat's Test Store: purchases are`,
    `    /// simulated (no Apple account, no real charges) but entitlements and`,
    `    /// webhooks behave like real ones. Use to badge test-mode UI.`,
    `    static let isTestStore = ${isTestStore ? "true" : "false"}`,
    `    /// Prefix that routes this app's webhook events to THIS Botflow project.`,
    `    static let appUserIdPrefix = ${prefixLiteral}`,
    "    static var isConfigured: Bool { !apiKey.isEmpty }",
    "    /// The App User ID to pass to Purchases.configure for a signed-in user.",
    "    static func namespacedAppUserId(_ userId: String) -> String {",
    "        appUserIdPrefix + userId",
    "    }",
    "}",
    "",
  ].join("\n");
}

/**
 * Write `Sources/Core/RevenueCatConfig.swift` into a Swift project's sandbox.
 * Always written for Swift projects (when the feature is enabled) so the agent
 * can reference `RevenueCatConfig` before the user finishes connecting.
 *
 * Key selection (see SwiftBuildKind): dev builds bake only the cached Test
 * Store sandbox key. If the RC project has no Test Store, dev builds receive
 * an empty key and Purchases stays disabled; they never fall back to `appl_`.
 * Release builds ALWAYS bake the `appl_` key — a Test Store key can never ship
 * to the App Store by construction. Keys only bake once this project is
 * 'connected'; otherwise the file carries an empty key.
 */
export async function materializeSwiftRevenueCatConfig(
  projectId: string,
  buildKind: SwiftBuildKind = "dev",
): Promise<void> {
  if (!REVENUECAT_ENABLED) return;
  const db = getDb();
  const [project] = await db.select().from(projects).where(eq(projects.id, projectId));
  if (!project || project.platform !== "swift") return;
  if (project.backendType === "none") return; // payments require a backend

  let config = { sdkKey: null as string | null, isTestStore: false };
  if (project.revenuecatStatus === "connected") {
    const [identity] = await db
      .select({
        rcPublicSdkKey: userRevenueCatIdentity.rcPublicSdkKey,
        rcTestStoreSdkKey: userRevenueCatIdentity.rcTestStoreSdkKey,
      })
      .from(userRevenueCatIdentity)
      .where(eq(userRevenueCatIdentity.userId, project.userId));
    config = selectSwiftRevenueCatConfig(
      {
        productionSdkKey: identity?.rcPublicSdkKey ?? null,
        testStoreSdkKey: identity?.rcTestStoreSdkKey ?? null,
      },
      buildKind,
    );
  }

  await sandboxWriteFile(
    projectId,
    SWIFT_REVENUECAT_CONFIG_PATH,
    swiftRevenueCatConfigContent(config.sdkKey, namespacedAppUserIdPrefix(projectId), config.isTestStore),
  );
}

/**
 * All platform-managed Swift config files, in one call. Use this at every
 * build entry point so no path can bake a stale or missing config. Pass
 * buildKind 'release' ONLY from the App Store submit path — everything else
 * (simulator preview, dev device installs, convex-deploy reseeds) is 'dev'
 * and gets the Test Store key.
 */
export async function materializeSwiftBuildConfig(
  projectId: string,
  buildKind: SwiftBuildKind = "dev",
): Promise<void> {
  await materializeSwiftConvexConfig(projectId);
  await materializeSwiftRevenueCatConfig(projectId, buildKind);
}
